{% set version = "2.11.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-phangorn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/phangorn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/phangorn/phangorn_{{ version }}.tar.gz
  sha256: 10096ecae03e118aa4dbc60d9866175fad4849c948e004cf10c3868e3feed420

build:
  merge_build_host: true  # [win]
  number: 1
  skip: true  # [r_base == "4.0"]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-matrix                   # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-ape                      # [build_platform != target_platform]
    - r-fastmatch                # [build_platform != target_platform]
    - r-igraph                   # [build_platform != target_platform]
    - r-quadprog                 # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-ape >=5.6
    - r-digest
    - r-fastmatch
    - r-generics
    - r-igraph >=1.0
    - r-quadprog
    - libblas
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-matrix
    - r-rcpp
    - r-ape >=5.6
    - r-digest
    - r-fastmatch
    - r-generics
    - r-igraph >=1.0
    - r-quadprog

test:
  commands:
    - $R -e "library('phangorn')"           # [not win]
    - "\"%R%\" -e \"library('phangorn')\""  # [win]

about:
  home: https://github.com/KlausVigo/phangorn
  license: GPL-2.0-or-later
  summary: 'Package contains methods for estimation of phylogenetic trees and networks using Maximum Likelihood, Maximum Parsimony, distance methods and Hadamard conjugation. Allows to compare trees, models selection and offers visualizations for trees and split networks. '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: phangorn
# Title: Phylogenetic Reconstruction and Analysis
# Version: 2.5.5
# Authors@R: c(person("Klaus", "Schliep", email="klaus.schliep@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0003-2941-0161")),  person("Emmanuel", "Paradis", role = c("aut"), comment = c(ORCID = "0000-0003-3092-2199")),  person("Leonardo", "de Oliveira Martins", role = c("aut"), comment = c(ORCID = "0000-0001-5247-1320")),  person("Alastair", "Potts", role = c("aut")),  person("Tim W.", "White", role = c("aut")), person("Cyrill", "Stachniss", role = c("ctb")), person("Michelle", "Kendall", email="m.kendall@imperial.ac.uk", role = c("ctb")),  person("Keren", "Halabi", role = c("ctb")), person("Richel", "Bilderbeek", role = c("ctb")), person("Kristin", "Winchell", role = c("ctb")))
# Maintainer: Klaus Schliep <klaus.schliep@gmail.com>
# Description: Package contains methods for estimation of phylogenetic trees and networks using Maximum Likelihood, Maximum Parsimony, distance methods and Hadamard conjugation. Allows to compare trees, models selection and offers visualizations for trees and split networks.
# Depends: R (>= 3.2.0), ape (>= 5.0)
# Imports: quadprog, igraph (>= 1.0), Matrix, parallel, methods, utils, stats, graphics, grDevices, fastmatch, magrittr, Rcpp (>= 0.12.0)
# LinkingTo: Rcpp
# Suggests: testthat, vdiffr, seqinr, xtable, rgl, knitr, rmarkdown, Biostrings
# License: GPL (>= 2)
# VignetteBuilder: utils, knitr
# URL: https://github.com/KlausVigo/phangorn
# BugReports: https://github.com/KlausVigo/phangorn/issues
# Repository: CRAN
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: yes
# Packaged: 2019-06-18 15:48:42 UTC; klaus
# Author: Klaus Schliep [aut, cre] (<https://orcid.org/0000-0003-2941-0161>), Emmanuel Paradis [aut] (<https://orcid.org/0000-0003-3092-2199>), Leonardo de Oliveira Martins [aut] (<https://orcid.org/0000-0001-5247-1320>), Alastair Potts [aut], Tim W. White [aut], Cyrill Stachniss [ctb], Michelle Kendall [ctb], Keren Halabi [ctb], Richel Bilderbeek [ctb], Kristin Winchell [ctb]
# Date/Publication: 2019-06-19 04:40:03 UTC
