{% set version = "2.12.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-phangorn
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/phangorn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/phangorn/phangorn_{{ version }}.tar.gz
  sha256: 9dc59c7806b4ba5d2d168d0504fdd5a10778aa24ef2c7014af92c3a2f1fe9ee7

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-matrix                     # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - r-ape                        # [build_platform != target_platform]
    - r-fastmatch                  # [build_platform != target_platform]
    - r-igraph                     # [build_platform != target_platform]
    - r-quadprog                   # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ compiler('fortran') }}    # [osx and arm64]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp
    - r-ape >=5.6
    - r-digest
    - r-fastmatch
    - r-generics
    - r-igraph >=1.0
    - r-quadprog
    - libblas
  run:
    - r-base
    - r-matrix
    - r-rcpp
    - r-ape >=5.6
    - r-digest
    - r-fastmatch
    - r-generics
    - r-igraph >=1.0
    - r-quadprog

test:
  commands:
    - $R -e "library('phangorn')"           # [not win]
    - "\"%R%\" -e \"library('phangorn')\""  # [win]

about:
  home: https://github.com/KlausVigo/phangorn
  license: GPL-2.0-or-later
  summary: 'Package contains methods for estimation of phylogenetic trees and networks using Maximum Likelihood, Maximum Parsimony, distance methods and Hadamard conjugation. Allows to compare trees, models selection and offers visualizations for trees and split networks. '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
