{% set version = "2.5.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-phangorn
  version: {{ version|replace("-", "_") }}

source:
  fn: phangorn_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/phangorn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/phangorn/phangorn_{{ version }}.tar.gz
  sha256: c58dc1ace26cb4358619a15da3ea4765dbdde1557acccc5103c85589a7571346

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rcpp >=0.12.0
    - r-ape >=5.0
    - r-fastmatch
    - r-igraph >=1.0
    - r-magrittr
    - r-quadprog
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix
    - r-rcpp >=0.12.0
    - r-ape >=5.0
    - r-fastmatch
    - r-igraph >=1.0
    - r-magrittr
    - r-quadprog

test:
  commands:
    - $R -e "library('phangorn')"           # [not win]
    - "\"%R%\" -e \"library('phangorn')\""  # [win]

about:
  home: https://github.com/KlausVigo/phangorn
  license: GPL (>= 2)
  summary: 'Package contains methods for estimation of phylogenetic trees and networks using
    Maximum Likelihood, Maximum Parsimony, distance methods and Hadamard conjugation.
    Allows to compare trees, models selection and offers visualizations for trees and
    split networks. '
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
